name: 'PageVitals Test Action'
description: 'Run PageVitals tests in your build pipeline and get performance metrics'
inputs:
  api_key:
    description: 'PageVitals API Key'
    required: true
  website_id:
    description: 'Website ID to run tests for'
    required: true
  pages:
    description: 'A list of page_ids and devices if you do not want to run tests for all pages'
    required: false
  description:
    description: 'A description that can be shown in PageVitals. Usually a deployment version or commit message.'
    required: false
  max_failed_tests:
    description: 'Maximum number of failed tests before this action fails. Defaults to no maximum.'
    required: false
  performance_threshold:
    description: 'Minimum average performance score threshold (0-100). Defaults to no threshold.'
    required: false
  accessibility_threshold:
    description: 'Minimum average accessibility score threshold (0-100). Defaults to no threshold.'
    required: false
  best_practices_threshold:
    description: 'Minimum average best practices score threshold (0-100). Defaults to no threshold.'
    required: false
  seo_threshold:
    description: 'Minimum average SEO score threshold (0-100). Defaults to no threshold.'
    required: false
  budgets_exceeded_threshold:
    description: 'Fail the action if the number of budgets exceeded surpasses this value. Defaults to no threshold.'
    required: false
outputs:
  test_results:
    description: 'JSON string containing the test results'
runs:
  using: 'composite'
  steps:
    - run: npm ci
      shell: bash
    - run: node ${{ github.action_path }}/src/index.js
      shell: bash
branding:
  icon: 'heart'
  color: 'green'
